# Generated by Django 3.2.8 on 2022-12-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_blogs', to='blog.summary'),
        ),
    ]
